name: My First Workflow

on: 
  schedule:
    - cron: "*/1 * * * *"

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: List and read Files
          run: |
            echo "My first github action"
            ls -ltrah
            cat README.md

        - name: Generate ASCII Artwork
          run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt  ## cowsay is a third party library which is used for generating ASCII artwork
          
        #- name: welcome message
         # run: echo "My first github action job"
        
        #- name: List files
        #  run: ls

       # - name: read file
        #  run: cat README.md

       