name: Generate ASCII Artwork

on:
  #push
   workflow_dispatch:

jobs:
  ascii_job:
    concurrency:
        group: production-deployment
        cancel-in-progress: true  # it will cancel any existing workflow and runs a new
    runs-on: ubuntu-latest
    steps:
    - name: Checkoutrepo
      uses: actions/checkout@v4

    - name: list Repo files
      run: ls -ltrah
    
    - name: Executing shell script
      timeout-minutes: 1
      run: | 
          chmod +x new-ascii-script.sh
          ls -ltrah
          ./new-ascii-script.sh
          sleep 6000s

