name: Generate ASCII Artwork

on:
  push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkoutrepo
      uses: actions/checkout@v4

    - name: list Repo files
      run: ls -ltrah
    
    - name: Executing shell script
      run: | 
          chmod +x ascii-script.sh
          ./ascii-script.sh

