name: Exploring variables and secrets
## Note we can define env variable at workflow level, job level or steps level
on:
  push
env:                                     ## this env variable defined at workflow level level
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: kunal1996
jobs:
    docker1:
        runs-on: ubuntu-latest
        steps:
            - name: dockerbuild
              env:
                CONTAINER_REGISTRY: docker.io  # this env variable defined at step level
              run: docker build -t $CONTAINER_REGISTRY/dockerUsername/imageName:latest

            - name: Docker Login
              run: docker login --username=${{vars.DOCKER_USERNAME}} --password=${{secrets.DOCKER_PASSWORD}}

            - name: Publish
              run: docker push dockerUsername/imageName:latest

    deploy:
        env:                                     # we have define env variable at job level
           CONTAINER_REGISTRY: docker.io
           DOCKER_USERNAME: kunal1996
        needs: docker1
        runs-on: ubuntu-latest
        steps:
        - name: docker deploy
          run: docker run -it -d -p 8080:80 $DOCKER_USERNAME/imageName:latest