name: exploring-workflow-filter and activity

on:
   workflow_dispatch:

   push:
      branches:
        - main
        - '!feature/*'  # ignoring pushing to any branch name starting with feature using !
    #branch_ignore:
     #   - feature/*    #the name of branch like feature/updateimages
      #  - test/**          # the name of branch like feature/checkout/payment
   pull_request:
    types:
        - opened
        - closed
    paths-ignore:
        - README.md

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - name: hello
              run: echo "hello world"